### ISSUE TITLE
Hi, the file in the dir of cifar10 and cifar100 used in lines 118-124 of "dataset.py" is not presented in the repo.

### ISSUE THREAD

**Issue by LanXiaoPang613** [whyandbecause/ECLB#2]
Hi, the file in the dir of cifar10 and cifar100 used in lines 118-124 of "dataset.py" is not presented in the repo.
![image](https://github.com/whyandbecause/ECLB/assets/35187545/d9743af5-bb2e-43b5-a52e-d1dbdbc88c2e)
![image](https://github.com/whyandbecause/ECLB/assets/35187545/4a9ab554-26f7-48cf-8032-9f5da994fb09)

**Comment by whyandbecause** [comment]
![屏幕截图 2024-06-27 213325](https://github.com/whyandbecause/ECLB/assets/16316888/b1a4a6a0-c3c0-4c15-991b-e9b18f654c4d)
Hi，You can refer to the return value of the __getitem__ function.
